<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Domain.fs" />
    <Compile Include="WireLevel.fs" />
    <Compile Include="Library.fs" />
    <Compile Include="Place.fs" />
    <Compile Include="Route.fs" />
    <Compile Include="Sta.fs" />
    <Compile Include="Sim.fs" />
    <Compile Include="Pipeline.fs" />
    <Compile Include="PipelineWL.fs" />
    <Compile Include="E2eTests.fs" />
  </ItemGroup>
</Project>
